177,0
S,ShiodaInvariants,,0,1,0,0,0,0,0,0,0,338,,82,-38,-38,-38,-38,-38
S,ShiodaInvariants,"Given a homogeneous binary octavic over K, return the invariants J2, J3, ..., J10 of Shioda, such that J2, J3, ..., J7 are algebraically independent and K[J2,...,J10] is a free K[J2,...,J7]-module of rank 5, generated by 1, J8, J9, J10, J9^2",0,1,0,0,0,0,0,0,0,63,,82,-38,-38,-38,-38,-38
